# Generated by Django 3.2.5 on 2021-07-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('SundayStart', models.IntegerField()),
                ('SundayEnd', models.IntegerField()),
            ],
        ),
    ]
