# Generated by Django 3.2.5 on 2021-07-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='FridayEnd',
            field=models.IntegerField(default='0', verbose_name='Friday End Time'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='FridayStart',
            field=models.IntegerField(default='0', verbose_name='Friday Start Time'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='MondayEnd',
            field=models.IntegerField(default='0', verbose_name='Monday End Time'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='MondayStart',
            field=models.IntegerField(default='0', verbose_name='Monday Start Time'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='SaturdayEnd',
            field=models.IntegerField(default='0', verbose_name='Saturday End Time'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='SaturdayStart',
            field=models.IntegerField(default='0', verbose_name='Saturday Start Time'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='ThursdayEnd',
            field=models.IntegerField(default='0', verbose_name='Thursday End Time'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='ThursdayStart',
            field=models.IntegerField(default='0', verbose_name='Thursday Start Time'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='TotalTime',
            field=models.IntegerField(default='0', verbose_name='Total Time'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='TuesdayEnd',
            field=models.IntegerField(default='0', verbose_name='Tuesday End Time'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='TuesdayStart',
            field=models.IntegerField(default='0', verbose_name='Tuesday Start Time'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='WednesdayEnd',
            field=models.IntegerField(default='0', verbose_name='Wednesday End Time'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='WednesdayStart',
            field=models.IntegerField(default='0', verbose_name='Wednesday Start Time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='SundayEnd',
            field=models.IntegerField(default='0', verbose_name='Sunday End Time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='SundayStart',
            field=models.IntegerField(default='0', verbose_name='Sunday Start Time'),
        ),
    ]
